export {
	Gender,
	Age,
	Height,
	Weight,
	SystolicBP,
	DiastolicBP,
	HeartRate,
	CigarettesPerDay,
	SmokingStatus,
	CholesterolIntake,
	GlucoseIntake,
	MaritalStatus,
	Pregnancies,
	WorkType,
	ResidenceType,
	DiabetesHistory,
	ChestPain,
	QuestionnaireComplete,
	default as Questionnaire,
} from "../Questionnaire";
