# Generated by Django 5.2 on 2025-04-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('systolicBP', models.IntegerField(blank=True, null=True)),
                ('diastolicBP', models.IntegerField(blank=True, null=True)),
                ('heartRate', models.IntegerField(blank=True, null=True)),
                ('cigarettesPerDay', models.IntegerField(blank=True, null=True)),
                ('smokingStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('cholesterolIntake', models.CharField(blank=True, max_length=50, null=True)),
                ('glucoseIntake', models.CharField(blank=True, max_length=50, null=True)),
                ('maritalStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('pregnancies', models.IntegerField(blank=True, null=True)),
                ('workType', models.CharField(blank=True, max_length=50, null=True)),
                ('residenceType', models.CharField(blank=True, max_length=50, null=True)),
                ('diabetesHistory', models.CharField(blank=True, max_length=50, null=True)),
                ('chestPain', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Questionnaire Response',
                'verbose_name_plural': 'Questionnaire Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
